/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.33
 * Generated at: 2013-10-10 00:24:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1349688243000L));
    _jspx_dependants.put("/top.jsp", Long.valueOf(1349731408000L));
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1349384799000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<title>Advocacia LCA</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/jquery-ui.css\"></link>\r\n");
      out.write("<script type='text/javascript' src='js/jquery-1.8.0.min.js'></script>\r\n");
      out.write("<script type='text/javascript' src='js/jquery-ui-1.8.23.custom.min.js'></script>\r\n");
      out.write("<script type='text/javascript' src='js/jquery.ui.datagrid.min.js'></script>\r\n");
      out.write("<script type='text/javascript' src='js/jquery-ui-timepicker-addon.js'></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/fancybox/jquery.mousewheel-3.0.4.pack.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/fancybox/jquery.fancybox-1.3.4.pack.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"js/fancybox/jquery.fancybox-1.3.4.css\" media=\"screen\" />\r\n");
      out.write("<script type='text/javascript' src='js/custom.jpro.js'></script>");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!-- fim  header -->\r\n");
      out.write("<!-- começo do topo -->\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"pack\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"top\">\r\n");
      out.write("        <img src=\"images/logo.png\" alt=\"\" >\r\n");
      out.write("        <div class=\"nav\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"index.jsp\">Início</a></li>\r\n");
      out.write("                <li><a href=\"processo\">Processos</a></li>\r\n");
      out.write("                <li><a href=\"honorario\">Honorários</a></li>\r\n");
      out.write("                <li><a href=\"audiencia\">Audiências</a></li>\r\n");
      out.write("                <li><a href=\"relatorio\">Relatórios</a></li>       \r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>      \r\n");
      out.write("<!-- fim do topo -->\r\n");
      out.write("    <div class=\"middle\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <h3>Início</h3> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table border=\"0\" width=\"600\">\r\n");
      out.write("<colgroup span=\"0\" width=\"300\" align=\"center\"></colgroup> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("     <tr>\r\n");
      out.write("          \t\t<td> \r\n");
      out.write("\t\t\t\t<td align=\"center\"><h2><a href=\"processo\">Processos </a></h2>\r\n");
      out.write("               <!-- <div style=\"float:left; width:33%\"></div> --> \r\n");
      out.write("                <div id=\"duas_imagens\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"imagem1\"></div>\r\n");
      out.write("\t\t\t\t<img src=\"images/processo.jpeg\" width=\"50\" height=\"50\" /></td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("          <td>\r\n");
      out.write("\r\n");
      out.write("          <td align=\"center\"><h2><a href=\"audiencia\">Audiências</a></h2>\r\n");
      out.write("                <div id=\"duas_imagens\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"imagem2\">\r\n");
      out.write("\t\t\t\t<center><img src=\"images/audiencia.jpeg\" width=\"50\" height=\"50\" />\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div></td>\r\n");
      out.write("          </td>\r\n");
      out.write("                   \r\n");
      out.write("          <td>\r\n");
      out.write("          <td align=\"center\"><h2><a href=\"relatorio\">Relatórios</a></h2> \r\n");
      out.write("                <div id=\"duas_imagens\"></div>\r\n");
      out.write("\t\t\t\t<div id=\"imagem3\">\r\n");
      out.write("\t\t\t\t<center><img src=\"images/relatorios.jpeg\" width=\"50\" height=\"50\" />\r\n");
      out.write("\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td> \r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("          </td>\r\n");
      out.write("\r\n");
      out.write("     </tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("           \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t           \r\n");
      out.write("                \r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- começo do footer -->\r\n");
      out.write("    <div class=\"footer\">\r\n");
      out.write("        <p>Todos os Direitos Reservados - Desenvolvido por <a href=\"#\">JPro</a></p>    \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("<!-- fim do footer -->");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
